server:
  port: 8081
spring:
  application:
    name: fraud
  datasource:
    username: 'iquark'
    url: jdbc:postgresql://localhost:5432/fraud
    password: '213111454'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'